"""add Department

Revision ID: 557eac1da477
Revises: f5f524f91b6f
Create Date: 2025-08-29 11:26:38.118610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557eac1da477'
down_revision = 'f5f524f91b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
